name: CI
on:
  push:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Modules
        run: npm install
      - name: Run Tests
        run: npm test
